require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Metaprog::MetaAttributesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Metaprog::MetaAttribute. As you add validations to Metaprog::MetaAttribute, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Metaprog::MetaAttributesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all metaprog_meta_attributes as @metaprog_meta_attributes" do
      meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:metaprog_meta_attributes)).to eq([meta_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested metaprog_meta_attribute as @metaprog_meta_attribute" do
      meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
      get :show, {:id => meta_attribute.to_param}, valid_session
      expect(assigns(:metaprog_meta_attribute)).to eq(meta_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new metaprog_meta_attribute as @metaprog_meta_attribute" do
      get :new, {}, valid_session
      expect(assigns(:metaprog_meta_attribute)).to be_a_new(Metaprog::MetaAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested metaprog_meta_attribute as @metaprog_meta_attribute" do
      meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
      get :edit, {:id => meta_attribute.to_param}, valid_session
      expect(assigns(:metaprog_meta_attribute)).to eq(meta_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Metaprog::MetaAttribute" do
        expect {
          post :create, {:metaprog_meta_attribute => valid_attributes}, valid_session
        }.to change(Metaprog::MetaAttribute, :count).by(1)
      end

      it "assigns a newly created metaprog_meta_attribute as @metaprog_meta_attribute" do
        post :create, {:metaprog_meta_attribute => valid_attributes}, valid_session
        expect(assigns(:metaprog_meta_attribute)).to be_a(Metaprog::MetaAttribute)
        expect(assigns(:metaprog_meta_attribute)).to be_persisted
      end

      it "redirects to the created metaprog_meta_attribute" do
        post :create, {:metaprog_meta_attribute => valid_attributes}, valid_session
        expect(response).to redirect_to(Metaprog::MetaAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metaprog_meta_attribute as @metaprog_meta_attribute" do
        post :create, {:metaprog_meta_attribute => invalid_attributes}, valid_session
        expect(assigns(:metaprog_meta_attribute)).to be_a_new(Metaprog::MetaAttribute)
      end

      it "re-renders the 'new' template" do
        post :create, {:metaprog_meta_attribute => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested metaprog_meta_attribute" do
        meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
        put :update, {:id => meta_attribute.to_param, :metaprog_meta_attribute => new_attributes}, valid_session
        meta_attribute.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested metaprog_meta_attribute as @metaprog_meta_attribute" do
        meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
        put :update, {:id => meta_attribute.to_param, :metaprog_meta_attribute => valid_attributes}, valid_session
        expect(assigns(:metaprog_meta_attribute)).to eq(meta_attribute)
      end

      it "redirects to the metaprog_meta_attribute" do
        meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
        put :update, {:id => meta_attribute.to_param, :metaprog_meta_attribute => valid_attributes}, valid_session
        expect(response).to redirect_to(meta_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the metaprog_meta_attribute as @metaprog_meta_attribute" do
        meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
        put :update, {:id => meta_attribute.to_param, :metaprog_meta_attribute => invalid_attributes}, valid_session
        expect(assigns(:metaprog_meta_attribute)).to eq(meta_attribute)
      end

      it "re-renders the 'edit' template" do
        meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
        put :update, {:id => meta_attribute.to_param, :metaprog_meta_attribute => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metaprog_meta_attribute" do
      meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => meta_attribute.to_param}, valid_session
      }.to change(Metaprog::MetaAttribute, :count).by(-1)
    end

    it "redirects to the metaprog_meta_attributes list" do
      meta_attribute = Metaprog::MetaAttribute.create! valid_attributes
      delete :destroy, {:id => meta_attribute.to_param}, valid_session
      expect(response).to redirect_to(metaprog_meta_attributes_url)
    end
  end

end
